Update demo to the latest Ably SDK
ably/queue-demo pull request #2
Opened 2018-03-05 18:03 UTC by funkyboy

2018-03-13 09:57 UTC, SimonWoolf requested changes

2018-03-13 09:57 UTC, SimonWoolf commented on package.json
> +        "ably": "ably/ably-js#1.0.13",
Now we don't need to use a prerelease we can use the npm version, like you did [here](https://github.com/ably/demo-mobile-phonegap-cordova/pull/10/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R11), we don't need to point to a github tag

2018-03-13 10:48 UTC, funkyboy commented
@SimonWoolf good catch. There's always something that slips through the cracks :)

2018-03-14 07:25 UTC, SimonWoolf approved these changes

2018-03-19 08:27 UTC, merged